// Autogenerated from Pigeon (v3.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class InitializeRequestData;
@class StartChatRequestData;

@interface InitializeRequestData : NSObject
+ (instancetype)makeWithAccountKey:(nullable NSString *)accountKey
    appId:(nullable NSString *)appId;
@property(nonatomic, copy, nullable) NSString * accountKey;
@property(nonatomic, copy, nullable) NSString * appId;
@end

@interface StartChatRequestData : NSObject
+ (instancetype)makeWithDepartment:(nullable NSString *)department
    name:(nullable NSString *)name
    email:(nullable NSString *)email
    phoneNumber:(nullable NSString *)phoneNumber
    iosBackButtonTitle:(nullable NSString *)iosBackButtonTitle
    iosNavigationBarColor:(nullable NSNumber *)iosNavigationBarColor
    iosNavigationTitleColor:(nullable NSNumber *)iosNavigationTitleColor
    userLanguageTag:(nullable NSString *)userLanguageTag
    licenseTag:(nullable NSString *)licenseTag
    brandTag:(nullable NSString *)brandTag
    codeTag:(nullable NSString *)codeTag;
@property(nonatomic, copy, nullable) NSString * department;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * phoneNumber;
@property(nonatomic, copy, nullable) NSString * iosBackButtonTitle;
@property(nonatomic, strong, nullable) NSNumber * iosNavigationBarColor;
@property(nonatomic, strong, nullable) NSNumber * iosNavigationTitleColor;
@property(nonatomic, copy, nullable) NSString * userLanguageTag;
@property(nonatomic, copy, nullable) NSString * licenseTag;
@property(nonatomic, copy, nullable) NSString * brandTag;
@property(nonatomic, copy, nullable) NSString * codeTag;
@end

/// The codec used by ChatApi.
NSObject<FlutterMessageCodec> *ChatApiGetCodec(void);

@protocol ChatApi
- (void)initializeRequest:(InitializeRequestData *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startChatRequest:(StartChatRequestData *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)endChatWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ChatApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ChatApi> *_Nullable api);

NS_ASSUME_NONNULL_END
