name: support_zendesk
description: Flutter interface for Zendesk Mobile SDK
version: 0.0.1
homepage: https://www.brainrocket.com/
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  support_zendesk_interface: {git: { url: git@github.com:Dersh/zendesk.git, path: zendesk/support_zendesk_interface, ref: 890eacd8f898e6f1cd5c6251260b70899ffd4a50 }}
  support_zendesk_android: {git: { url: git@github.com:Dersh/zendesk.git, path: zendesk/support_zendesk_android, ref: 890eacd8f898e6f1cd5c6251260b70899ffd4a50 }}
  support_zendesk_ios: {git: { url: git@github.com:Dersh/zendesk.git, path: zendesk/support_zendesk_ios, ref: 890eacd8f898e6f1cd5c6251260b70899ffd4a50 }}

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        default_package: support_zendesk_android
      ios:
        default_package: support_zendesk_ios
